<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefaultItemExcludes>$(DefaultItemExcludes);._*</DefaultItemExcludes>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ryujinx.Common\Ryujinx.Common.csproj" />
    <InternalsVisibleTo Include="Ryujinx.Tests.Memory" />
  </ItemGroup>

</Project>
